---
- name: Configure Rocky server
  hosts: all
  become: yes

  tasks:

    - name: Install all the software needed
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - bash-completion       
        - vim
        - git
        - podman-docker

    - name: Create the rocky user
      user:
        name: rocky
        create_home: yes
        home: /home/rocky
        shell: /bin/bash

    - name: Add rocky user to sudoers
      copy:
        dest: /etc/sudoers.d/rocky
        content: "rocky ALL=(ALL) NOPASSWD: ALL"
    - name: create hosts file
      copy:
        dest: "/etc/hosts"
        content: |
          192.168.2.100    rocky1
          192.168.2.101    rocky2